name: 'Bug report'
description: Report a defect in the website or CI/CD
labels: ['bug']
title: '[Bug]: '
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? A clear, concise description of the bug.
      placeholder: The contact form returns 500 when submitting...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the issue.
      placeholder: |
        1. Go to /contact
        2. Fill out the form
        3. Click Submit
        4. Observe error
    validations:
      required: true

  - type: input
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: e.g., Form submits and shows success message
    validations:
      required: true

  - type: input
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: e.g., 500 error with stack trace
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options: ['Critical', 'High', 'Medium', 'Low']
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Logs / Screenshots
      description: Paste relevant logs, screenshots, or links.
      placeholder: Drag and drop images, paste stack traces, or link to Sentry/Application Insights.
