name: Bug report
description: Report a reproducible defect on the company website.
title: '[Bug]: '
type: bug
projects: ['modelversebv/2']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please include clear reproduction steps so we can fix it quickly.

  - type: checkboxes
    id: dupe_check
    attributes:
      label: Is there an existing issue targeting the same bug?
      description: Please search open issues before filing a new one.
      options:
        - label: I have searched existing issues
          required: true

  - type: input
    id: affected_url
    attributes:
      label: URL(s) affected
      description: Full page URL(s) where the bug occurs.
      placeholder: 'https://www.example.com/path'
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity (impact)
      description: How disruptive is this issue?
      options:
        - Critical — crash/security/blank page
        - High — page/functionality broken for most users
        - Medium — degraded behavior/workaround exists
        - Low — minor visual/content issue
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the expected behaviour, and what is the current behaviour?
      placeholder: 'Describe the bug.'
    validations:
      required: true

  - type: textarea
    id: repro_steps
    attributes:
      label: Steps to reproduce
      description: Walk us through the exact steps.
      placeholder: |
        1. Go to …
        2. Click …
        3. Observe …

  - type: dropdown
    id: device
    attributes:
      label: Specific to device(s)
      description: Only fill in if applicable
      multiple: true
      options:
        - Desktop
        - Laptop
        - Tablet
        - Mobile

  - type: dropdown
    id: browsers
    attributes:
      label: Specific to browser(s)
      description: Only fill in if applicable
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Microsoft Edge

  - type: dropdown
    id: os
    attributes:
      label: Specific to operating system(s)
      description: Only fill in if applicable
      multiple: true
      options:
        - macOS
        - Windows
        - Linux
        - iOS
        - Android

  - type: input
    id: version
    attributes:
      label: Build version
      description: Version number of the build where the bug is present.

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Any other details, screenshots, logs, or hypotheses.
