blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/modelversebv/modelverse-website/discussions/new
    about: Use Discussions for questions or ideas not ready for the backlog.
