name: Epic
description: A large body of work composed of multiple subfeatures.
title: '[Epic]: '
type: epic
projects: ['modelversebv/2']

body:
  - type: markdown
    attributes:
      value: |
        Use this to keep track of large bodies of work composed of multiple subfeatures.

  - type: checkboxes
    id: dupe_check
    attributes:
      label: Is there an existing issue targeting the same bug?
      description: Please search open issues before filing a new one.
      options:
        - label: I have searched existing issues
          required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: High-level overview of the epic.
      placeholder: 'What is this epic about and why does it matter?'
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: In Scope
      description: Features, pages, and other components which are part of this epic.
      placeholder: |
        - Feature A
        - Page B
        - Integration with XYZ

  - type: textarea
    id: child_issues
    attributes:
      label: Child issues
      description: Link stories/tasks using a checklist.
      placeholder: |
        - [ ] #123 Story: …
        - [ ] #124 Task: …
        - [ ] #125 Feature: …
    validations:
      required: true
