name: Task
description: A general engineering or operational task.
title: '[Task] <area-or-component>: <summary>'
type: task
# labels: ["task", "needs-triage"]
# projects: ["<org-or-user>/<project-number>"]

body:
  - type: markdown
    attributes:
      value: |
        Use this for one-off tasks, maintenance, chores, and operational work.

  - type: input
    id: area
    attributes:
      label: Area / component
      placeholder: 'e.g., CI/CD, Infra, Analytics, Content'

  - type: textarea
    id: description
    attributes:
      label: Task description
      description: What needs to be done?
      placeholder: 'Explain the steps, context, and desired outcome.'
    validations:
      required: true

  - type: textarea
    id: subtasks
    attributes:
      label: Subtasks (checklist)
      description: Use markdown checkboxes to break down work.
      placeholder: |
        - [ ] Step 1…
        - [ ] Step 2…
        - [ ] Verify…

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 — urgent/critical
        - P1 — high
        - P2 — medium
        - P3 — low
      default: 2

  - type: input
    id: due_date
    attributes:
      label: Due date (optional)
      placeholder: 'YYYY-MM-DD'

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies / related issues
      placeholder: '- Blocked by: #456, Vendor input'

  - type: textarea
    id: resources
    attributes:
      label: References / resources
      description: Links to docs, runbooks, examples.
      render: markdown

  - type: checkboxes
    id: dod
    attributes:
      label: Definition of Done
      options:
        - label: Work completed
        - label: Verified by reviewer/stakeholder
        # - label: Monitoring/alerts updated (if relevant)
