name: 'Task'
description: General work item (docs, CI, refactor, maintenance)
labels: ['task']
title: '[Task]: '
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Set up GitHub Actions cache for Node modules...
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: Checklist
      description: Break work into steps.
      placeholder: |
        - [ ] Implement
        - [ ] Tests
        - [ ] Update docs
    validations:
      required: false

  - type: input
    id: depends_on
    attributes:
      label: Depends on
      description: Link any blocking issues (e.g., #123, #124).
